### ISSUE TITLE
Missing parts of sentences

### ISSUE THREAD

**Issue by aulorbe** [learn-co-curriculum/dsc-04-40-02-introduction-to-neural-networks#2]
We'll need some expression here in order to predict **??** The parameters here are  w∈ℝnw∈Rn  and  b∈ℝb∈R . Some expression to get to  ŷ y^  could be  ŷ =wTx+by^=wTx+b . The problem here is, however, that this type of expression does not ensure that the eventual outcome  ŷ y^ will be between zero and one, and it could be much bigger than one or even negative! A popular solution is to **??**

**Comment by fpolchow** [comment]
fixed, thanks for flagging :)
